name: "CI"
on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install Nix
        uses: cachix/install-nix-action@v15

      - name: Build
        run: nix develop --command make build

      - name: Test
        run: nix develop --command make tests

      - name: Generate docs
        run: nix develop --command make docs

      - name: Deploy Docs to GH Pages
        if: { { github.ref == 'ref/head/main' } }
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: generated-docs/html
